### PR TITLE
fix(server): handle OpenCode text response format in commit message g…

### LINKED ISSUE #2199: [Bug]: OpenCode returns "no structured output" error during commit message generation
### Before submitting

- [x] I searched existing issues and did not find a duplicate.
- [x] I included enough detail to reproduce or investigate the problem.

### Area

apps/server

### Steps to reproduce

1. Configure T3 Code to use OpenCode as the text generation provider for git operations
2. Stage some changes in a git repository
3. Trigger the "Commit" or "Commit and Push" action from the UI
4. The operation fails with the structured output error

### Expected behavior

The commit should successfully complete with a commit message. Tested with Claude Code (Haiku) and this works fine.

### Actual behavior

The operation fails with the error: `"Text generation failed in generateCommitMessage: OpenCode returned no structured output."`

### Impact

Major degradation or frequent failure

### Version or commit

main @ 9df3c640

### Environment

- macOS 15.6.1 - Bun 1.3.12 - OpenCode CLI 1.14.18 - OpenCode provider configured for text generation

### Logs or stack traces

```shell
Action failed Error: Text generation failed in generateCommitMessage: OpenCode returned no structured output.
```

### Screenshots, recordings, or supporting files

[image.png](https://github.com/user-attachments/assets/eca4af0e-ee4f-4484-8214-c91939416b26)

### Workaround

Switch to Codex or Claude providers for git text generation operations.

### PR DESCRIPTION
**Pull request by imabdulazeez**
## What Changed

- Updated the OpenCode git text-generation path to read JSON from text parts in the prompt response instead of requiring `info.structured`.
- Surface OpenCode's returned structured-output error message when the provider reports one, and keep failing fast on empty responses.
- Reused the existing JSON-object extraction logic from the Cursor implementation and moved it into `apps/server/src/git/Utils.ts` as shared logic so OpenCode and Cursor parse provider output the same way.
- Updated `apps/server/src/git/Layers/OpenCodeTextGeneration.test.ts` to cover the failing OpenCode response shapes: empty output, JSON returned inside plain text parts, and upstream structured-output errors.
- Tested both OpenCode and Cursor for git text generation to confirm the shared JSON extraction path still works for each provider.

## Why

OpenCode is currently returning the generated payload as plain text parts rather than populating `info.structured`, so the existing implementation treated valid responses as failures and broke commit message generation.

Parsing the returned text locally and decoding it against the existing schema keeps the validation path intact while matching the response shape OpenCode actually sends.

### Before

image

### After

image

## Checklist

- [x] This PR is small and focused
- [x] I explained what changed and why
- [x] I included before/after screenshots for any UI changes
- [ ] I included a video for animation/interaction changes (not applicable)

Closes #2199

> [!NOTE]
> ### Fix OpenCode text response parsing in commit message generation
> - Removes the `json_schema` structured output format from OpenCode requests; instead reads raw text parts and extracts JSON locally using `extractJsonObject` from [Utils.ts](https://github.com/pingdotgg/t3code/pull/2202/files#diff-1ee616952fa622d2c71d75cb27872f6de2db838eec8e9f9b38b0fea34bf11b7a).
> - Adds `getOpenCodeTextResponse` to concatenate text parts into a single string, and `getOpenCodePromptErrorMessage` to surface upstream `info.error` details as thrown errors.
> - Throws a typed `'OpenCode returned empty output.'` error when no text parts are present, and maps `info.error` with `StructuredOutputError` to a readable message.
> - Moves `extractJsonObject` to [Utils.ts](https://github.com/pingdotgg/t3code/pull/2202/files#diff-1ee616952fa622d2c71d75cb27872f6de2db838eec8e9f9b38b0fea34bf11b7a) and shares it with [CursorTextGeneration.ts](https://github.com/pingdotgg/t3code/pull/2202/files#diff-3d4564ebce0d6acfab1c1c06f09893d415f4c983f5326dfdadad90894e2a244f).
> - Behavioral Change: OpenCode prompts no longer request structured JSON output; JSON is parsed client-side from plain text responses.
>
> 
>
> <sup><a href="https://app.macroscope.com">Macroscope</a> summarized 2a12331.</sup>
> 
>

### CODE REVIEW

File: apps/server/src/git/Layers/OpenCodeTextGeneration.ts [hunk 1]
```diff
@@ -245,17 +288,18 @@ const makeOpenCodeTextGeneration = Effect.gen(function* () {
             ...(input.modelSelection.options?.variant
               ? { variant: input.modelSelection.options.variant }
               : {}),
-            format: {
-              type: "json_schema",
-              schema: toJsonSchemaObject(input.outputSchemaJson) as Record<string, unknown>,
-            },
```
Comment (juliusmarminge) [inline apps/server/src/git/Layers/OpenCodeTextGeneration.ts:251]: cc @nexxeln is your structured data not reliable?
