### PR TITLE
fix(web): allow deleting non-empty projects from the warning toast

### LINKED ISSUE #665: Feature: Option to delete non-empty Project
# Status quo
Given I have a project with more than one thread
When I want to delete the project
Then the UI blocks that, asking me to delete all threads first

Image

# Proposal
Instead of the notification, open a dialog to confirm deletion of non-empty project: "Deleting `<project>` will also delete all threads" -> confirm/cancel

### PR DESCRIPTION
**Pull request by maria-rcks**
## What Changed

Adds a `Delete anyway` button to the `Project is not empty` warning toast.

Clicking it closes the toast, asks for confirmation, then deletes the project's threads and removes the project.

closes #665

## Why

Right now the warning blocks project deletion without giving you a way to continue.

This keeps the fix small and makes the warning actionable.

## Video

https://github.com/user-attachments/assets/89bd5cbe-0bba-41f6-830f-2cd10005d00a

> [!NOTE]
> ### Allow force-deleting non-empty projects from the sidebar with cascading thread cleanup
> - Adds a `force` flag to the `project.delete` command schema; the decider rejects non-empty project deletions unless `force=true`, in which case it emits `thread.deleted` events for each active thread before `project.deleted`.
> - The sidebar now shows a warning toast with a destructive 'Delete anyway' action for non-empty projects, triggering a confirmation dialog before dispatching a forced delete.
> - Introduces `ThreadDeletionReactor`, a new server-side service that listens for `thread.deleted` events and performs best-effort cleanup by stopping provider sessions and closing terminals.
> - Draft thread state and image blob URLs associated with the project are cleared when the project is deleted.
> - Toast UI is extended to support stacked action layout and configurable button variants (e.g. `destructive`).
>
> 
>
> <sup><a href="https://app.macroscope.com">Macroscope</a> summarized e2d953d.</sup>
> 
>

---

> [!NOTE]
> **Medium Risk**
> Changes orchestration deletion semantics and introduces a new background reactor that stops sessions/closes terminals; incorrect sequencing or missed wiring could lead to data loss or leaked runtime resources.
> 
> **Overview**
> Enables deleting a non-empty project from the sidebar by surfacing a warning toast with a **destructive** “Delete anyway” action that re-dispatches `project.delete` with `force=true` after confirmation.
> 
> On the server, `project.delete` now supports an optional `force` flag: without it, deleting a project with active threads is rejected; with it, the decider plans a sequence of `thread.deleted` events for each active thread before emitting `project.deleted`. A new `ThreadDeletionReactor` is wired into the runtime to react to `thread.deleted` events and best-effort stop provider sessions and close terminals.
> 
> Client-side cleanup is tightened: toasts support stacked action layout/variants, composer drafts revoke image blob URLs when cleared, and `project.deleted` events clear any project-scoped draft mapping.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit e2d953d876f51153977143a9c59d52b499a17001. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: apps/web/src/components/Sidebar.tsx [hunk 1]
```diff
@@ -1219,46 +1248,57 @@ export default function Sidebar() {
...
+                    "This action cannot be undone.",
+                  ].join("\n"),
+                );
+                if (!confirmed) return;
+
+                const deletedThreadIds = new Set<ThreadId>(projectThreadIds);
+                for (const threadId of projectThreadIds) {
+                  await deleteThread(threadId, { deletedThreadIds });
+                }
+                await removeProject(projectId);
```
Comment (juliusmarminge) [inline apps/web/src/components/Sidebar.tsx]: will this slow down the frontend? should we do it server side with some `force: true` flag and then do the deletions from there?
