### PR TITLE
fix: fix external link opening in desktop

### LINKED ISSUE #434: Open external link doesn't work - MacOS
When trying to open an external link the app does nothing.
I tried in different threads but it doesn't change anything.

https://github.com/user-attachments/assets/78c825dc-8259-4f97-a053-dad451993123

### PR DESCRIPTION
**Pull request by Noojuno**
## What Changed

Added electron link handling for safe links so they open in an external browser.

I have validated that file links still open in Cursor, and that external links work in both the browser and desktop environment.

## Why

Clicking on external links in the agent response was doing nothing rather than opening in an external browser.

Fixes #434

## Checklist

- [x] This PR is small and focused
- [x] I explained what changed and why
- [x] I included before/after screenshots for any UI changes
- [x] I included a video for animation/interaction changes

> [!NOTE]
> ### Validate and open http/https external links from desktop by routing `main.createWindow` window-open requests and `main.registerIpcHandlers` `OPEN_EXTERNAL` through `main.getSafeExternalUrl` in [main.ts](https://github.com/pingdotgg/t3code/pull/599/files#diff-31a471f6ef958ceff6e87ee910f4bc4f7bbc4986f797f159353b328a5916f7cb)
> Add `main.getSafeExternalUrl` to normalize and guard URLs; update `OPEN_EXTERNAL` IPC handler and `webContents.setWindowOpenHandler` to use it and open validated links via `shell.openExternal` in [main.ts](https://github.com/pingdotgg/t3code/pull/599/files#diff-31a471f6ef958ceff6e87ee910f4bc4f7bbc4986f797f159353b328a5916f7cb).
>
> #### 📍Where to Start
> Start with `getSafeExternalUrl` and its use in the `OPEN_EXTERNAL` IPC handler and `webContents.setWindowOpenHandler` in [main.ts](https://github.com/pingdotgg/t3code/pull/599/files#diff-31a471f6ef958ceff6e87ee910f4bc4f7bbc4986f797f159353b328a5916f7cb).
>
> 
>
> <sup><a href="https://app.macroscope.com">Macroscope</a> summarized 015ee56.</sup>
> 
>

### CODE REVIEW

File: apps/desktop/src/main.ts [hunk 1]
```diff
@@ -112,6 +112,25 @@ function formatErrorMessage(error: unknown): string {
...
+  let parsedUrl: URL;
+  try {
+    parsedUrl = new URL(rawUrl);
+  } catch {
+    return null;
+  }
+
+  if (parsedUrl.protocol !== "https:" && parsedUrl.protocol !== "http:") {
+    return null;
+  }
```
Comment (binbandit) [inline apps/desktop/src/main.ts]: what about deep-linking into other apps etc?

**Comment by t3dotgg** [comment]
Legend ty!

**Comment by eefan000** [comment]
This feature is still invalid on Windows
